### PR TITLE
Remove deprecated getParseDir

### PR DESCRIPTION
**Pull request by Jawnnypoo**
Remove access and replace usages with the non-deprecated method

### CODE REVIEW

**Comment by natario1** [comment]
I think you should provide some legacy mechanism?

Like, if the old version was saving stuff in folderA, and the new version checks in folderB, the device is in a unexpected state. I haven't seen what kind of files were saved there though

**Comment by Jawnnypoo** [comment]
This method was not public, and was only used by the SDK itself, and the `getParseCacheDir` points to the same folder, it just assures the directory exists beforehand. So, nothing really changes, this is just to remove some deprecation

**Comment by natario1** [comment]
AFAIK they should be different, I remember wanting to do the same but I was kind of stuck #679 for this legacy thing..

**Comment by Jawnnypoo** [comment]
I see, I'll just close this for now then, thanks

**Pull request closed without merging**
