### PR TITLE
Fix ParseUserCurrentCoder bug

### PR DESCRIPTION
**Pull request by natario1**
Fixes a bug that would make session token be `JSONObject.NULL` instead of `null`, causing #209 .

### CODE REVIEW

**Comment by jhansche** [comment]
Looks like another unit test is failing because of this now.

**Comment by natario1** [comment]
@rogerhu the second there will just hide the bug when present, this should actually go to the point and fix it. 

I think we could merge this and then, if the bug is still present from some other source, consider the other

**Comment by rogerhu** [comment]
rebase

**Comment by natario1** [comment]
What's wrong with travis? We just merged a few comments. Tests pass on my machine.. 😕

**Comment by flovilmart** [comment]
There seems to be an issue in the ParseInstallationTests

**Comment by natario1** [comment]
Looks related to the travis worker time zone, let's see. It's strange that it showed up now

**Pull request merged**
