### PR TITLE
ci: Upgrade CI JDK from 11 to 17

### PR DESCRIPTION
**Pull request by abubkr-hago**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Android/issues/1214).

### Issue Description
CI is using JDK 11 which is not supported by the newer AGP 8.5.2.

Closes: [#1214](https://github.com/parse-community/Parse-SDK-Android/issues/1214).

### Approach
Upgrade JDK to 17.

### TODOs before merging

- [x] No tests required
- [x] No documentation required.

### CODE REVIEW

**Comment by mtrezza** [comment]
@abubkr-hago why did you close this PR?

**Comment by mtrezza** [comment]
@abubkr-hago if you have a few minutes it would be great if you could ping on me Slack for a quick chat.

**Comment by abubkr-hago** [comment]
> @abubkr-hago if you have a few minutes it would be great if you could ping on me Slack for a quick chat (unrelated to this PR)

It is my pleasure, I sent you an invitation to a TempWorkspace on slack and a dm.

**Comment by mtrezza** [comment]
Thank you, do you think you could join our [Slack](https://chat.parseplatform.org) and send me a message there?

**Pull request closed without merging**
