### PR TITLE
Add link to ParseLiveQuery

### PR DESCRIPTION
**Pull request by natario1**
Adding a public link to ParseLiveQuery among “Other Parse Projects"

### CODE REVIEW

**Comment by rogerhu** [comment]
rebase

**Comment by natario1** [comment]
@rogerhu there you go. Speaking about front page, I think you should also edit the repo description, has a broken link to parse.com , should be parseplatform.org

**Comment by rogerhu** [comment]
rebase

**Comment by rogerhu** [comment]
sorry =)

**Pull request merged**
