### PR TITLE
Use the right builder

### PR DESCRIPTION
**Pull request by Jawnnypoo**
Fixes https://github.com/parse-community/Parse-SDK-Android/issues/636

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Pulled this in locally using jitpack and I can confirm this fixes it. @rogerhu Please take a look when you get a moment.

**Comment by rogerhu** [comment]
Do we need the same for fileClient?

**Comment by Jawnnypoo** [comment]
fileClient is actually not including the interceptor that the restClient is, which means it is not including the app id, client key etc. This was the case with 1.14.1 https://github.com/parse-community/Parse-SDK-Android/blob/1.14.1/Parse/src/main/java/com/parse/ParseFileController.java I guess file operations do not require those headers?

**Comment by rogerhu** [comment]
Great.  I've released 1.15.1 to Maven (should take a few hours to sync).  In the meantime, I think you either need a custom OkHttpClient or simply use 1.14.1.  Thanks for the quick verification!

**Pull request merged**
