### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by Jawnnypoo**
This is mostly just cleanup of lint errors found by Android Studio in the project. I tried to break up the commits by the type of lint error it was, but some commits cover a few things at once

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
I don't really think there is anything I can do about that first failure on codecov

**Comment by flovilmart** [comment]
Nah not really, but this is OK, as we don't require the status to merge.

**Comment by Jawnnypoo** [comment]
@rogerhu Is there something blocking this?

**Comment by rogerhu** [comment]
Nope I think the review required stuff throws me off.

**Comment by Jawnnypoo** [comment]
Good to merge now, @rogerhu ?

**Comment by rogerhu** [comment]
rebase

**Comment by Jawnnypoo** [comment]
@rogerhu Done!

**Pull request merged**
