### PR TITLE
Include dependency & references shield in README

### PR DESCRIPTION
**Pull request by addisonElliott**
Add a dependency shield that determines if the dependencies in the repository are up to date. If not, the shield will indicate out of date and this will notify contributors that the libraries need to be updated.

In addition, a references shield is included which shows the number of projects that reference this project.

These two badges are included in the Android-SDK-iOS-OSX project and it is nice to stay consistent between the various projects of Parse. Badges are obtained via VersionEye.

### CODE REVIEW

**Comment by rogerhu** [comment]
Now can you help bump our version too. :)

Rebase needed.

**Comment by addisonElliott** [comment]
Sure thing, I can update the version. That should be a separate pull request, right?

Why is a rebase needed, I'm not sure I understand.

**Comment by rogerhu** [comment]
Your READMe.md file probably conflicts with the version that I just merged in... there are some conflicts currently (see resolve conflicts button)

**Comment by addisonElliott** [comment]
Thank you, I noticed the button right after I sent my message...

It should be good to go now.

**Pull request merged**
