### PR TITLE
Annotate nullable methods on ParseObject

### PR DESCRIPTION
**Pull request by kurtisnelson**
This makes the object linter/Kotlin friendly.

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Nice, I was thinking this would be a good addition for Kotlin support. I'll probably expand on this for the put methods, as well as for other classes like ParseQuery

**Comment by Jawnnypoo** [comment]
Should need any docs, but it's with noting that if someone is upgrading to the next version and using Kotlin, they might see build exceptions, since it will change things from String to String? etc

**Comment by kurtisnelson** [comment]
That's good build breakage.

**Comment by Jawnnypoo** [comment]
Of course! Just something to note and potentially a reason to make the next version a 1.18.0

**Pull request merged**
