### PR TITLE
Allow setting of max retries

### PR DESCRIPTION
**Pull request by Jawnnypoo**
Presently, the number of retries of a Parse command is always set to 5, and is not changeable. This allows you to set the number of max retries via the Parse.Configuration. Example:

```
 val config = Parse.Configuration.Builder(this)
                .applicationId("test")
                .clientKey("blah")
                .server("https://example.com/parse")
                .maxRetries(2)
                .build()
```
or even disable retries by setting `maxRetries(0)`

### CODE REVIEW

**Comment by natario1** [comment]
+10 for removing ParsePlugins.Android, such a headache. Looks good to me.

**Comment by addisonElliott** [comment]
If I get time, I'll check this out. 

@Jawnnypoo Wanted to let you know that this was on my (long) TODO list and I'm glad you submitted a PR for this! :thumbsup:

**Comment by rogerhu** [comment]
@addisonElliott if you can check it out that would be much appreciated =)

**Comment by addisonElliott** [comment]
Looks good to me. I pulled it locally and tested it out.

On a sidenote, what is the purpose of `userAgent` in the `ParsePlugins` class? It seems it is not used in Parse Android SDK and it is a private package, so it cannot be called. It may be worthwhile to create a function in Parse.java that calls this function. I can submit the PR if you would like.

**Pull request merged**
