### PR TITLE
fix: missing pending intents mutability for Android 12+

### LINKED ISSUE #1137: Android12 raises a Exception with onPushReceive
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Android SDK](https://github.com/parse-community/Parse-SDK-Android/releases). 

### Issue Description
     The following exception is raised with Android12 when onPushReceive is called.
     And targetSDKVersion is 31.

     Caused by: java.lang.IllegalArgumentException: my.package: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.parse.ParsePushBroadcastReceiver.getNotification(ParsePushBroadcastReceiver.java:430)
        at com.parse.ParsePushBroadcastReceiver.onPushReceive(ParsePushBroadcastReceiver.java:168)

### Steps to reproduce
Call ParsePushBroadcastReceiver#onPushReceive method.

### Actual Outcome
Caused by: java.lang.IllegalArgumentException: my.package: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.parse.ParsePushBroadcastReceiver.getNotification(ParsePushBroadcastReceiver.java:430)
        at com.parse.ParsePushBroadcastReceiver.onPushReceive(ParsePushBroadcastReceiver.java:168)

### Expected Outcome
No exception.

### Environment
any Parse Android SDK version with Android12 and targetSDKVersion 31

Parse Android SDK
- SDK version: `2.0.3`
- Operating system version: `Android12`

### PR DESCRIPTION
**Pull request by L3K0V**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).

### Issue Description

Pending intents mutability

If your app targets Android 12, you must specify the mutability of each PendingIntent object that your app creates. This additional requirement improves your app's security.

https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

Related issue: #1137
Closes #1137 

### Approach

Freeze version of the compile and target to the newest version 31 and on Android 12 versions set PendingIntent immutability flags when receiving Parse notifications.

### TODOs before merging

- [ ] ~Add tests~
- [ ] ~Add changes to documentation (guides, repository pages, in-code descriptions)~
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by L3K0V** [comment]
@mtrezza I cannot understand the failing CI/CD task. This PR should be done.

**Comment by mtrezza** [comment]
The CI fails because this PR decreases code coverage. We want PR to at least cover their own changes.

**Comment by L3K0V** [comment]
@mtrezza I have add some tests for building the notifications but and I patched the ParseCommandCache as there ware some null pointer exceptions when there's no internet permissions on the tests. Please ignore if possible `codecov/patch`

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.0.6](https://github.com/parse-community/Parse-SDK-Android/releases/tag/2.0.6)

**Pull request merged**
