### PR TITLE
Move over to JitPack

### PR DESCRIPTION
**Pull request by Jawnnypoo**

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
@rogerhu Were you thinking something like this for the `latest.version.here` thing?

**Comment by Jawnnypoo** [comment]
Going to repurpose this to moving over to JitPack

**Comment by flovilmart** [comment]
Why to move?

**Comment by Jawnnypoo** [comment]
I misunderstood, I was thinking we were going to move over to it for all dependencies, but we are likely going to just move over to it for snapshots.

**Pull request closed without merging**
