### PR TITLE
Support for Full Text Search

### PR DESCRIPTION
**Pull request by dplewis**
Closes: https://github.com/parse-community/Parse-SDK-Android/issues/751

I did run into issues with 27 API Licensing but resolved it.

### CODE REVIEW

**Comment by dplewis** [comment]
@rogerhu Can you look this over?

**Comment by rogerhu** [comment]
Thanks for adding!

**Comment by rogerhu** [comment]
FYI - I think the [docs](http://docs.parseplatform.org/rest/guide/#schema) need to be improved.  Kept getting `text index required for $text query` error codes even after trying to use the Schema API.  I had to manually add the text query to the index even after using the API:

```bash
curl -X POST \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-Master-Key: ${MASTER_KEY}" \
  -H "Content-Type: application/json" \
  -d '
    {
      "className": "GameScore",
      "fields": {
        "playerName": {
          "type": "String"
        }
      },
      "indexes": {
        "indexName": {
          "playerName": 1 
        }
      }
    }' \
  http://localhost:1337/parse/schemas/GameScore
```

This fixed the problem:

```
db.GameScore.createIndex({playerName: "text"})
```

**Comment by dplewis** [comment]
@rogerhu what version of Parse-server are you running. Text indexes should be automatically created.

**Comment by rogerhu** [comment]
`MongoDB shell version v3.6.2`

The Schema API creates an index, but not a text index:

```
[
	{
		"v" : 2,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "parse.GameScore"
	},
	{
		"v" : 2,
		"key" : {
			"playerName" : 1
		},
		"name" : "indexName",
		"ns" : "parse.GameScore"
	},
```

Only by calling the Mongo specific index does it work:

```
	{
		"v" : 2,
		"key" : {
			"_fts" : "text",
			"_ftsx" : 1
		},
		"name" : "playerName_text",
		"ns" : "parse.GameScore",
		"weights" : {
			"playerName" : 1
		},
		"default_language" : "english",
		"language_override" : "language",
		"textIndexVersion" : 3
	}
```

**Comment by rogerhu** [comment]
I was also using the latest commit 8ec07b83d0b74b00153b7b414aa73d7247c55f85 of Parse-Server

**Comment by rogerhu** [comment]
Dropping the table and SCHEMA info and re-creating the table doesn't help either:

```
> db.GameScore.drop()
true
> db.getCollection("_SCHEMA").remove({"_id": "GameScore"})
WriteResult({ "nRemoved" : 1 })
```

POST to create some data:

```bash
curl -X POST \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-Master-Key: ${MASTER_KEY}" \
  -H "Content-Type: application/json" \
  -d '{"score":1337,"playerName":"Sean Plott","cheatMode":false}'  \
  http://localhost:1337/parse/schemas/GameScore
```

Mongo:

```bash
> db.getCollection("_SCHEMA").find({"_id": "GameScore"})
{ "_id" : "GameScore", "objectId" : "string", "updatedAt" : "date", "createdAt" : "date" }
> db.GameScore.getIndexes()
[ ]
```

**Comment by rogerhu** [comment]
I put a breakpoint but don't ever see [createIndexesIfNeeded()](https://github.com/parse-community/parse-server/blob/8ec07b83d0b74b00153b7b414aa73d7247c55f85/src/Adapters/Storage/Mongo/MongoStorageAdapter.js#L588) get called either

**Comment by dplewis** [comment]
For the schema you could do 
```
 "indexes": {
        "indexName": {
          "playerName": "text"
        }
      }
```

Thats interesting if createTextIndexesIfNeeded() isn't called. I'll look into it

**Comment by rogerhu** [comment]
It seems like I have to explicitly use the "text" field instead of 1 (https://github.com/parse-community/Parse-SDK-Android/pull/772#issuecomment-357449220):

```bash
curl -X POST \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-Master-Key: ${MASTER_KEY}" \
  -H "Content-Type: application/json" \
  -d '
    {
      "className": "GameScore",
      "fields": {
        "playerName": {
          "type": "String"
        }
      },
      "indexes": {
        "indexName": {
          "playerName": "text"
        }
      }
    }' \
  http://localhost:1337/parse/schemas/GameScore
```

Then it seems to work:

```bash
> use parse
switched to db parse
> db.GameScore.getIndexes()
[
	{
		"v" : 2,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "parse.GameScore"
	},
	{
		"v" : 2,
		"key" : {
			"_fts" : "text",
			"_ftsx" : 1
		},
		"name" : "indexName",
		"ns" : "parse.GameScore",
		"weights" : {
			"playerName" : 1
		},
		"default_language" : "english",
		"language_override" : "language",
		"textIndexVersion" : 3
	}
]
```

Again, it seems like the documentation needs to reflect this aspect.  It seems like text fields get added if you add new fields to an existing class right?

**Comment by rogerhu** [comment]
Yep @dplewis that worked.

**Comment by dplewis** [comment]
@rogerhu I can update the docs. When `whereFullText()` gets called the server looks for `$text` inside of `createTextIndexesIfNeeded()`. Can you debug `createTextIndexesIfNeeded`

**Comment by rogerhu** [comment]
Yeah I revised my comment.  Create text indexes never gets fired.  It seems like it passes in directly the create index command from the dictionary.

**Comment by dplewis** [comment]
`text index required for $text query` You shouldn't see this error in the current parse-server 2.7.1

**Comment by rogerhu** [comment]
That error is coming back from Mongo, not Parse server I believe.

**Comment by dplewis** [comment]
Ah, I see

**Comment by montymxb** [comment]
Thanks @dplewis & @rogerhu for getting this in!

**Pull request merged**
