### PR TITLE
Bump to 1.16.5

### PR DESCRIPTION
**Pull request by mmimeault**

### CODE REVIEW

**Comment by rogerhu** [comment]
You need to release this version for auto deploy to Bintray... 

* Tag a release; 1.16.5
* Add description of PR's that have changed:

```
* Add support for Support for Full Text Search thanks to @dplewis ([#772](https://github.com/parse-community/Parse-SDK-Android/pull/772))
* Update to Android API 27 thanks to @Jawnnypoo ([#760](https://github.com/parse-community/Parse-SDK-Android/pull/760))

See https://github.com/parse-community/Parse-SDK-Android/compare/1.16.3...1.16.4 for full changelog.
```

**Comment by rogerhu** [comment]
Sonatype was down so I just synced through the Bintray interface the 1.16.5 update.

image

**Comment by flovilmart** [comment]
Thanks @rogherhu

**Comment by mmimeault** [comment]
Yes thanks @rogerhu this is what I did, @flovilmart explained me the whole process. 
I bumped to snapshot when I was able to fetch the latest version from Bintray. The build failed probably because of Sonatype like you mentioned. Thanks for the sync that has failed.

**Comment by rogerhu** [comment]
Yeah the Gradle Bintray plugin should do it automatically (https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/build.gradle#L234-L239) but I think Sonatype was down.

I verify a few hours later by looking at gradleplease.appspot.com.

**Pull request merged**
