### PR TITLE
perf: remove unnecessary extra child traversal in collectDirtyChildren

### PR DESCRIPTION
**Pull request by shlusiak**
Please see https://github.com/parse-community/Parse-SDK-Android/issues/1006#issuecomment-682448919 for the analysis of this.

The `collectDirtyChildren` forgets seen siblings when traversing, which causes extra traversals if those siblings point to the same objects and causes lots of garbage to be created in memory. It also has the potential of adding the same dirty object twice to the `dirtyChildren` collection, which may or may not be a set.

Removing the copy of the `seen` set may improve performance significantly.

Should hopefully massively improve the situations described in issues #1006, #1007, possibly #888 and #993 .

### CODE REVIEW

**Comment by shlusiak** [comment]
The function in question actually has a few more issues:
- It uses a `HashSet` for `seen`, which means that the object's `equals()` and `hashCode()` functions will be used. So if two different ParseObjects implement equals over a set of attributes other than the objectId, this code will wrongly detect a cycle. Note that the `ParseTraverser` uses a `IdentityHashMap`.
- Whenever a ParseObject is visited, recursion is used to traverse this object. However, by calling `collectDirtyChildren`, a new `ParseTraverser` is instantiated with the current object as the root, which then of course has forgotten all of the previously visited objects and traverse them all again. This is obviously bad, I can't see how this would cause an infinite loop, but it is for sure exploding the algorithm to a point where it may never finish.

**Comment by mtrezza** [comment]
@shlusiak Apologies for the late reply to your PR, we are finally looking to close all PRs. Could you merge master into this and resolve any conflicts?

**Comment by mtrezza** [comment]
Thanks! Could you also add a test that to prevent the issue from occurring in the future?

**Comment by mtrezza** [comment]
@shlusiak I see, looks like not worth the effort because difficult to test. So let's merge as is.

**Review by L3K0V — APPROVED** [review]
@mtrezza LGTM

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.0.4](https://github.com/parse-community/Parse-SDK-Android/releases/tag/2.0.4)

**Pull request merged**
