### PR TITLE
fix: failed signup attempt with anonymous ParseUser leaves it in inconsistent state

### PR DESCRIPTION
**Pull request by shlusiak**
### Issue Description
The key "authData" contains a `Map` of authentication related data. Because unfortunately `estimatedData` is a shallow copy of `state`, the object pointed to by `state["authData"]` and `estimatedData["authData"]` is the same object. Modifying the data in this map directly prevents us from being able to call `revert()` to revert the data back to the server state.

This is impotant e.g. when trying to revert the user after converting it from anonymous to registered fails, where anonymity has been stripped and there is no way to get it back. 

Related issue: #401

### Approach
This would just create another (shallow) copy of "authData", which in this case would be fine, because we are only modifying the first layer. By replacing the value of the map with a new map we ensure that the values in `state` and `estimatedData` are different and that `revert()` works.

### CODE REVIEW

**Review by L3K0V — APPROVED** [review]
@shlusiak great job again, LGTM!

**Comment by L3K0V** [comment]
@shlusiak can you check please the failing test

```
com.parse.ParseUserTest > testSaveAsyncWithLazyAndCurrentUser FAILED
1579
    java.lang.AssertionError at ParseUserTest.java:962
```

**Comment by shlusiak** [comment]
@L3K0V I think I fixed the failing test. Let's see if it passes now.

**Comment by L3K0V** [comment]
@mtrezza LGTM

**Review by mtrezza — APPROVED** [review]
Look good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.0.5](https://github.com/parse-community/Parse-SDK-Android/releases/tag/2.0.5)

**Pull request merged**
