### PR TITLE
feat: update project dependencies and code refactoring

### PR DESCRIPTION
**Pull request by L3K0V**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).

### Issue Description

The project should be up-to-date with all dependencies, Gradle version, Android Studio etc but is not.
It uses an old versions of the integration libraries like Firebase, Facebook and also the Parse Android SDK is stuck on very old version of OkHttp which does not support newer TLS versions. Updating OkHttp requires bump of min Android SDK version to API 21. Also the new Firebase libraries also bump their min version to API 19

Also some of the modules uses deprecated APIs from Bolts and other libraries. The idea is to update the source base a bit.

Related issue: #1142 #1100 #1123 https://github.com/parse-community/Parse-SDK-Android/pull/1095
Closes: #1142

### Approach

The approach here will be to update all dependencies, Gradle wrapper version and AGP to the latest versions. Also cleaning up all deprecated code calls and replace them with their new options or variants. Because there was no activity and new Parse Android SDK versions lately, it's save to remove all deprecated Parse APIs.

### Breaking changes

- Minimum Android SDK API level is now 21
- Removed deprecated twitter link methods
- Removed deprecated `Parse.getParseDir()`

### TODOs before merging

- [ ] ~Add tests~
- [ ] ~Add changes to documentation (guides, repository pages, in-code descriptions)~
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by L3K0V** [comment]
@mtrezza in continue of https://github.com/parse-community/Parse-SDK-Android/pull/1095 I did another batch of dependencies updates to all modules dependencies and update again everything. Unfortunately it's time to update min SDK version to 21 as we discussed in #1123 because of two reasons:

1. Firebase requires now min SDK API 19
2. OkHttp requires min SDK API 21

The discussion here https://github.com/parse-community/Parse-SDK-Android/issues/1123#issuecomment-942281184

Fortunately the upgrades went smooth so far without big changes.

**Comment by L3K0V** [comment]
@mtrezza again this PR is baby step ahead. I have updated the description adding the breaking changes this PR introduce. And because there was no activity on the Android SDK if you are okay I decide to clean up and remove the deprecated methods Parse Android SDK provides, so it will be less code to maintain and to migrate to Kotlin after that.

**Comment by mtrezza** [comment]
@L3K0V you marked this as DRAFT after requesting the review. Do you still request the review and if yes, in what state is this PR?

**Comment by L3K0V** [comment]
Sorry @mtrezza, I found few things which I should improve soon.

**Review by mtrezza — APPROVED** [review]
Looks good, that's a pretty nice clean-up!

It seems this will be a major release as it will contain some breaking changes:
- minSdkVersion 16 to 21
- com.google.firebase:firebase-messaging 22.0.0 to 23.0.0 --> this does not have to mentioned explicitly, as it requires minSDK 19 which is lower than the bump to 21, but was google play services required for 22 as well?
- many deprecated public methods have been removed, they should be listed explicitly in the release notes, could you list them here in a comment, so I can use that to compose the braking change note?

**Comment by L3K0V** [comment]
@mtrezza here you go:

> but was google play services required for 22 as well?

In the release notes they say nothing about bumping the API level, but the release we use (the latest available) is from July, so I expect soon new versions to be released.

## Deprecated methods:

### Parse
- getParseDir() use getParseCacheDir(String) or getParseFilesDir(String) instead

### Twitter Utils 
- link(ParseUser, Context) use linkInBackground(Context, ParseUser) instead
- link(ParseUser, String, String, String, String) use linkInBackground(ParseUser, String, String, String, String) instead

I wonder how to compose an COMPATIBILITY.md or something similar to define the API levels supported and close also https://github.com/parse-community/Parse-SDK-Android/issues/1123 I'm open for ideas. Can you help me with this?

**Comment by L3K0V** [comment]
@mtrezza maybe I didn't get you right about 

> but was google play services required for 22 as well?

I think still Google Play Services are required for all versions of Firebase Messaging. In the [release notes](https://firebase.google.com/support/release-notes/android#messaging_v23-0-0) they said that:

> Due to its dependency on Google Play services, this SDK now requires devices and emulators to target API level 19 (KitKat) or higher and to use Android 4.4 or higher.

So I expect that they still depend on it. Also [here](https://firebase.google.com/docs/android/android-play-services) is mentioned that cloud messaing still requires Google Play Services

**Comment by mtrezza** [comment]
Yes, I have seen that table, but I couldn't tell from it whether they only added the Google Play Services dependency with version 23 but Cloud Messaging wasn't dependent on it in version 22. But if you say it was dependent also in version 22 then it's not a breaking change we need to mention.

**Comment by mtrezza** [comment]
I'm suggesting this breaking note in the release notes, any additions/changes?

BREAKING CHANGE: The required minimum API level changes from 16 to 21. The following deprecated methods are removed: `Parse.getParseDir()` (use `getParseCacheDir(String)` or `getParseFilesDir(String)` instead), `ParseTwitterUtils.link(ParseUser, Context)` (use `linkInBackground(Context, ParseUser)` instead), `ParseTwitterUtils.link(ParseUser, String, String, String, String)` (use `linkInBackground(ParseUser, String, String, String, String)` instead).

**Comment by L3K0V** [comment]
@mtrezza I have added some [Compatibility section](https://github.com/L3K0V/Parse-SDK-Android/tree/keep-dependencies-up-to-date#compatibility). It would be great if you check it.

**Comment by mtrezza** [comment]
I've made some changes to the compatibility table and moved the "min API level" rule into the CONTRIBUTING doc, as it's  more relevant for contributors than for users.

**Review by mtrezza — COMMENTED** [review]
I've made some changes to the compatibility table and moved the API level rules into the CONTRIBUTING doc, as it's more relevant for contributors than for developers. Could you review these changes and let me know if the wording is fine? Then we should be good to merge.

**Comment by L3K0V** [comment]
LGTM

**Review by mtrezza — APPROVED** [review]
Looks good to me too!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.2.0](https://github.com/parse-community/Parse-SDK-Android/releases/tag/2.2.0)

**Pull request merged**
