### PR TITLE
added warning to update server URL docs

### PR DESCRIPTION
**Pull request by mtrezza**
added docs warning for updating server URL, to keep docs the same as in Android SDK.

https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1464#issuecomment-557964378

### CODE REVIEW

**Comment by mtrezza** [comment]
Merge only after https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1464 has been merged.

**Comment by Jawnnypoo** [comment]
Can you update this based on the feedback on the iOS PR?

**Comment by mtrezza** [comment]
@Jawnnypoo what feedback specifically are you referring to?

**Comment by Jawnnypoo** [comment]
Ah I misread the conversation on that PR. I think this is good to merge then, right?

**Comment by mtrezza** [comment]
@Jawnnypoo Yes, this PR is to update the docs to be the same as in the Android SDK. I thought you were referring to something specific. Yes, good to merge 👍

**Pull request merged**
