### PR TITLE
ci: Fix codecov not reporting

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).

### Issue Description

Codecov not reporting, see:

https://github.com/parse-community/Parse-SDK-Android/actions/runs/10430424460/job/28890986911?pr=1213

### Approach

Fix codecov.

### CODE REVIEW

**Comment by abubkr-hago** [comment]
I think code coverage is incorrectly configured in the gradle build, I opened index.html in `parse/build/jacoco/jacocoHtml` and it looks like it is producing a 100% missed coverage.

jacoco_html
Can you confirm this as well?

**Comment by mtrezza** [comment]
I haven't tested this locally, but that may be what is causing the 0 coverage.

**Comment by mtrezza** [comment]
@abubkr-hago Good news, I got the coverage report working. The tests were not executed hence no coverage. Bad news, 9 tests are failing. Would you want to look into how to fix them?

**Comment by abubkr-hago** [comment]
**Nice Work**, I'll definitely give them a look.

**Comment by abubkr-hago** [comment]
>The tests were not executed hence no coverage.
If you meant the tests were not running locally, can you try changing AndroidStudio JDK to 11 and try with JUnitPlatform enabled?.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.4.0](https://github.com/parse-community/Parse-SDK-Android/releases/tag/4.4.0)

**Pull request merged**
