### PR TITLE
Add withinPolygon to Query

### PR DESCRIPTION
**Pull request by dplewis**
https://github.com/parse-community/parse-server/pull/3866

I haven't used java in a while so any help will be great

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
@flovilmart Do we support this on iOS? Seems like something we would want parity on

**Comment by flovilmart** [comment]
The PR is open on the iOS SDK as well, we're also trying to figure out how to keep track of SDK required changes properly (and even better automatically)

**Comment by addisonElliott** [comment]
Why has this pull request not been merged?

**Comment by natario1** [comment]
What's the status of this in other repos?

@dplewis would it be easy for you to add Local Datastore support? It should be a few lines additions in `OfflineQueryLogic` I think. There is also `OfflineQueryLogicTest` with samples. But I am not sure if it's an easy task, what do you think?

**Comment by dplewis** [comment]
@natario1 @addisonElliott `withinPolygon` is in all other SDKs. For Local Datastore I need an efficient pointInPolygon function. I have some time to day to update the android sdk

**Comment by natario1** [comment]
@dplewis that would be great! Thanks for the effort.

**Comment by natario1** [comment]
@dplewis what do you think about refactoring whereWithinPolygon to accept a `ParsePolygon`? I think it would be better now, not sure if you already planned

**Comment by dplewis** [comment]
@natario1 Do you mean something like this?

```
public ParseQuery<T> whereWithinPolygon(String key, Object value) {
    ParsePolygon polygon = null;

    if (value instanceof ParsePolygon) {
      polygon = (ParsePolygon)value;
    }
    if (value instanceof List) {
      polygon = new ParsePolygon((List<ParseGeoPoint>)value);
    }
    builder.whereGeoWithin(key, polygon.getCoordinates());
    return this;
  }
```

**Comment by dplewis** [comment]
I will change it to support both. 

The query builder will still have to use a list of coordinates for now until this PR goes through https://github.com/parse-community/parse-server/pull/4067

**Comment by natario1** [comment]
Great... thanks man!

We should add docs for this and #696 some day

**Comment by flovilmart** [comment]
Can you open issues on the docs repo for it?

**Pull request merged**
