### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by natario1**
Bump to 1.16.0

### CODE REVIEW

**Comment by rogerhu** [comment]
Please tag and release.  It should auto upload to Bintray.  Ping me if there is an issue.  Once we confirm the version is out we can bump to the next snapshot ver.

**Comment by natario1** [comment]
Just did it @rogerhu

**Comment by rogerhu** [comment]
https://travis-ci.org/parse-community/Parse-SDK-Android/builds/267989439?utm_source=email&utm_medium=notification

On Aug 24, 2017 7:03 AM, "Mattia Iavarone" <notifications@github.com> wrote:

Just did it @rogerhu <https://github.com/rogerhu>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/parse-community/Parse-SDK-Android/pull/721#issuecomment-324644596>,
or mute the thread

**Comment by natario1** [comment]
Cool so let's move to snapshot

**Pull request merged**
