### PR TITLE
refactor: replace startActivityForResult with ActivityResultLauncher

### PR DESCRIPTION
**Pull request by Shvet**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Android/issues/1151).

### Issue Description

Related issue: 
startActivityForReuslt was deprecated in adnroidx and replace with ActivityResultLauncher. So i have edited `Login` method and added `ActivityResultLauncher<Intent>` as a variable. 

### Approach

`login` method has new variable for `ActivityResultLauncher<Intent>` which can be replaced for `startActivityForResult`.
for example:
```
 val launcher: ActivityResultLauncher<Intent> = registerForActivityResult(
      ActivityResultContracts.StartActivityForResult()) { result ->
      ParseGoogleUtils.onActivityResult(result.resultCode, result.data!!)
 }

 // Login Using ParseGoogleUtils
 ParseGoogleUtils.logIn(requireContext(), launcher) { user, e -> }

```

### TODOs before merging

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@Shvet can you please make sure to consider all checkboxes at the top?

**Comment by Shvet** [comment]
> @Shvet can you please review all checkboxes in the description? Could you also take a look at the lint issue reported?

@mtrezza do i have to create issue for this? i didn't find any for this pull? AS for lint i have run `:spotlessApply` please check it.

**Comment by mtrezza** [comment]
> do i have to create issue for this?

that would be helpful, we want to separate issue discussion from PR (solution) discussion.

**Comment by Shvet** [comment]
Added [issue](https://github.com/parse-community/Parse-SDK-Android/issues/1151)

**Comment by mtrezza** [comment]
@L3K0V Do you think we can merge this?

**Comment by L3K0V** [comment]
@mtrezza LGTM

**Review by L3K0V — APPROVED** [review]

**Review by L3K0V — APPROVED** [review]

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.0.1](https://github.com/parse-community/Parse-SDK-Android/releases/tag/3.0.1)

**Pull request merged**
