### PR TITLE
Fixed exception handling in EventuallyPin.findAllPinned()

### PR DESCRIPTION
**Pull request by DanGTZ**

### CODE REVIEW

**Comment by DanGTZ** [comment]
iOS?

**Comment by flovilmart** [comment]
Us. Sorry stupid autocorrect

**Comment by DanGTZ** [comment]
@flovilmart does my explanation helped you? No problem to close the pull request if you don't want this improvement.

**Comment by DanGTZ** [comment]
@flovilmart I can see the "codecov/path" check failed, what can I do to solve this?

**Comment by flovilmart** [comment]
This means that the changes (patch) are not covered by a test at all.

**Pull request closed without merging**
