### PR TITLE
Allow the GcmBroadcastReceiver to be subclassed

### PR DESCRIPTION
**Pull request by mmimeault**
You can only define one Broadcast Receiver to act as a GCM receiver.
In our case, we want to receive pushes from Parse and another provider. So I was going to write a Proxy that wrap both receivers.

But the Parse SDK prevent that by doing a strong validation of the Manifest. (https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ManifestInfo.java#L446-L448)
The GCM receiver defined need to be explicitly an instance of GcmBroadcastReceiver.
And that class can't be extended as the onReceive method is final.
(If the validations do not pass, the PushType is None and the registration will not happen) (https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ManifestInfo.java#L212-L214)

The current PR is a proposition.
But there are many solutions to my problem.
- Remove the final
- Remove the strong validation
- other suggestion

### CODE REVIEW

**Comment by natario1** [comment]
Just curious, how are you going to get the gcm receiver instance to call `add` on it?

**Comment by mmimeault** [comment]
In the constructor of a class extending it. (protected method). You call add for each other receiver.

But I would prefer just remove the `final` on the onReceive signature.
I don't really understand why the SDK add that limitation.

One or the other is good for me.

**Comment by natario1** [comment]
I would also rather remove the `final` and maybe add the `@CallSuper` annotation

**Comment by Jawnnypoo** [comment]
@CallSuper is a part of the support annotations library, which Parse does not currently have as a dependency. But I would be happy if it did!

**Comment by natario1** [comment]
I think we have it.. ? https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/build.gradle#L47

**Comment by Jawnnypoo** [comment]
Ahh, I stand corrected. +1 for `@CallSuper` then!

**Comment by natario1** [comment]
Not sure when it was introduced, but it would be great to also annotate the rest of the SDK (thinking mostly of @Nullable and @NonNull )

**Comment by mmimeault** [comment]
Anyway... it doesn't work because of that
https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ManifestInfo.java#L368-L378

The class declared needs to be GcmBroadcastReceiver.class, not only an instanceOf.

Do anybody know why there is so much validation around that GCM receiver?
https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ManifestInfo.java#L212-L214

We are using mixpanel push system and we want also to use parse for differents campaign.
I would really like to have both working together.

**Comment by rogerhu** [comment]
Speaking of which, does anyone have bandwidth to consider ripping out GCMService and putting them into a separate repo?  Sort of like ParseGCM like we have for Parse Facebook.

This way people can start using Firebase GCM v4 but this library would provide all the necessary setup to make things work with Parse (i.e. InstandID service)

See: https://github.com/parse-community/Parse-SDK-Android/issues/445

**Comment by Jawnnypoo** [comment]
@rogerhu Do you think it needs to be its own repo?  Maybe it would be better to just have it as another module in this repo? (which could be deployed as its own dependency)

**Comment by rogerhu** [comment]
I think the challenge is that when you deploy via Gradle, it will attempt to deploy across all modules unless you explicitly specify it.

If it makes things easier to get started, we can do it until we're ready to release..

**Comment by rogerhu** [comment]
rebase

**Comment by rogerhu** [comment]
one more rebase needed

**Comment by racheal31ayers** [comment]
On Apr 27, 2017 1:04 PM, "Roger Hu" <notifications@github.com> wrote:

rebase

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/parse-community/Parse-SDK-Android/pull/638#issuecomment-297777261>,
or mute the thread

**Pull request merged**
