### PR TITLE
Change to use non-deprecated methods for registering FCM push token

### PR DESCRIPTION
**Pull request by Jawnnypoo**
This allows us to no longer need to register two services to set up FCM push. We will need to update the docs as well in the docs repo. This should probably be in a 1.20.0 update, since it breaks compatibility if others were extending our instance ID service.

### CODE REVIEW

**Comment by rogerhu** [comment]
https://medium.com/android-school/firebaseinstanceidservice-is-deprecated-50651f17a148 

Thanks!

**Comment by NicksonYap** [comment]
Sorry to bring this up, but on

Parse-SDK-Android 1.20.0 (parse and fcm)
Samsung S9, Android 9 (pie)
SDK 28

`deviceToken` and `pushType` will be empty when added as new Installation

initially I did a workaround to manually get the token from `FirebaseInstanceId.getInstance().getInstanceId()` and then run `setDeviceToken` and save on the installation (took a very long time to figure this out)

Turns out, it's already handled by the library, but instructions were missing in docs (this PR removed it from the docs)

The following is required in manifest:

```
         <service
            android:name="com.parse.fcm.ParseFirebaseInstanceIdService"
            android:exported="true">
            <intent-filter>
               <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
         </service>
```

and magically, the `deviceToken` and `pushType` will be set

Likely related to:
https://github.com/parse-community/Parse-SDK-Android/issues/886
https://github.com/parse-community/Parse-SDK-Android/issues/890

**Comment by davimacedo** [comment]
@NicksonYap would you be willed to send a new PR with the change that can improve the docs regarding this?

**Comment by FridaySG** [comment]
Thank you for catching that @NicksonYap :)

However, a separate service in the manifest is not necessary because ParseFirebaseMessagingService extends FirebaseMessagingService and therefore is called when a new deviceToken is generated. As seen here:

https://github.com/parse-community/Parse-SDK-Android/blob/7417db52564a763303eef6c79b2507cf3d5a5ef3/fcm/src/main/java/com/parse/fcm/ParseFirebaseMessagingService.java#L14

And referenced in the firebase docs:

https://firebase.google.com/docs/cloud-messaging/android/client#monitor-token-generation

The following should do the trick:


        <service
            android:name="com.parse.fcm.ParseFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>

Although to be honest I'm not even sure the "INSTANCE_ID_EVENT" is necessary, as per the firebase docs linked above.

Here is a piece of code I added to my initial activity in order to continually monitor/update device token as necessary in the even of a bug resulting in the device token not being generated:

```
            FirebaseInstanceId.getInstance().getInstanceId()
                    .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                        @Override
                        public void onComplete(@NonNull Task<InstanceIdResult> task) {
                            if (!task.isSuccessful()) {
                                Log.d("PUSH ID", "getInstanceId failed", task.getException());
                                return;
                            }

                            // Get new Instance ID token
                            String token = task.getResult().getToken();
                            installation.setDeviceToken(token);
                            installation.saveInBackground();
                            Log.d("PUSH ID", token);
                        }
                    });
```

**Pull request merged**
